name: real_shop_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  http: ^0.12.2
  intl: ^0.16.1
  provider: ^4.3.2+3
  responsive_grid: ^1.2.1+1
  shared_preferences: ^0.5.12+4
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: true
  image_path: "assets/images/shop.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/product-placeholder.png

  fonts:
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
